In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
import warnings
warnings.filterwarnings('ignore')

In [9]:
from mlxtend.frequent_patterns import apriori

In [10]:
from mlxtend.frequent_patterns import association_rules

In [11]:
data=pd.read_csv(r'D:/DATA SCIENCE/ASSIGNMENT/AS1/book.csv')

In [12]:
data.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

In [13]:
for i in data.columns:
    print(i)
    print(data[i].value_counts())
    print()

ChildBks
ChildBks
0    1154
1     846
Name: count, dtype: int64

YouthBks
YouthBks
0    1505
1     495
Name: count, dtype: int64

CookBks
CookBks
0    1138
1     862
Name: count, dtype: int64

DoItYBks
DoItYBks
0    1436
1     564
Name: count, dtype: int64

RefBks
RefBks
0    1571
1     429
Name: count, dtype: int64

ArtBks
ArtBks
0    1518
1     482
Name: count, dtype: int64

GeogBks
GeogBks
0    1448
1     552
Name: count, dtype: int64

ItalCook
ItalCook
0    1773
1     227
Name: count, dtype: int64

ItalAtlas
ItalAtlas
0    1926
1      74
Name: count, dtype: int64

ItalArt
ItalArt
0    1903
1      97
Name: count, dtype: int64

Florence
Florence
0    1783
1     217
Name: count, dtype: int64

In [14]:
data_p=pd.get_dummies(data)

In [15]:
data_p

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,1,0,0,1,1,1,0,1,1
1996,0,0,0,0,0,0,0,0,0,0,0
1997,0,0,0,0,0,0,0,0,0,0,0
1998,0,0,1,0,0,0,0,0,0,0,0
1999,0,0,0,0,0,0,0,0,0,0,0

In [16]:
formula=apriori(data_p,min_support=0.0001,use_colnames=True,max_len=3)
formula.sort_values('support',ascending=False)

     support                         itemsets
2     0.4310                        (CookBks)
0     0.4230                       (ChildBks)
3     0.2820                       (DoItYBks)
6     0.2760                        (GeogBks)
12    0.2560              (CookBks, ChildBks)
..       ...                              ...
219   0.0040    (ItalAtlas, ArtBks, Florence)
228   0.0040  (ItalCook, ItalAtlas, Florence)
230   0.0040   (ItalAtlas, Florence, ItalArt)
145   0.0035  (ItalAtlas, Florence, YouthBks)
194   0.0030  (DoItYBks, ItalAtlas, Florence)

[231 rows x 2 columns]

In [17]:
formula1=apriori(data_p,min_support=0.4,use_colnames=True,)
formula1

   support    itemsets
0    0.423  (ChildBks)
1    0.431   (CookBks)

In [18]:
formula2=apriori(data_p,min_support=0.2,use_colnames=True)
formula2

   support             itemsets
0   0.4230           (ChildBks)
1   0.2475           (YouthBks)
2   0.4310            (CookBks)
3   0.2820           (DoItYBks)
4   0.2145             (RefBks)
5   0.2410             (ArtBks)
6   0.2760            (GeogBks)
7   0.2560  (CookBks, ChildBks)

In [19]:
formula3=apriori(data_p,min_support=0.001,use_colnames=True)
formula3

      support                                           itemsets
0      0.4230                                         (ChildBks)
1      0.2475                                         (YouthBks)
2      0.4310                                          (CookBks)
3      0.2820                                         (DoItYBks)
4      0.2145                                           (RefBks)
...       ...                                                ...
2042   0.0015  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...
2043   0.0010  (ItalCook, ItalArt, ItalAtlas, ChildBks, GeogB...
2044   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...
2045   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, GeogBk...
2046   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...

[2047 rows x 2 columns]

In [20]:
formula3.sort_values("support",ascending=False)

      support                                           itemsets
2       0.431                                          (CookBks)
0       0.423                                         (ChildBks)
3       0.282                                         (DoItYBks)
6       0.276                                          (GeogBks)
12      0.256                                (CookBks, ChildBks)
...       ...                                                ...
1879    0.001  (ItalCook, ItalArt, ChildBks, ArtBks, Florence...
1309    0.001  (ItalArt, CookBks, ItalAtlas, Florence, YouthB...
1883    0.001  (ItalCook, ItalArt, ChildBks, GeogBks, Florenc...
1884    0.001  (ItalArt, ItalAtlas, ChildBks, GeogBks, Floren...
2046    0.001  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...

[2047 rows x 2 columns]

In [21]:
asso=association_rules(formula,metric="lift",min_threshold=0.0)
asso

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(YouthBks),(ChildBks),0.2475,0.4230,0.165,0.666667,1.576044,0.060308,1.731000,0.485714
1,(ChildBks),(YouthBks),0.4230,0.2475,0.165,0.390071,1.576044,0.060308,1.233750,0.633449
2,(CookBks),(ChildBks),0.4310,0.4230,0.256,0.593968,1.404179,0.073687,1.421069,0.505870
3,(ChildBks),(CookBks),0.4230,0.4310,0.256,0.605201,1.404179,0.073687,1.441240,0.498856
4,(DoItYBks),(ChildBks),0.2820,0.4230,0.184,0.652482,1.542511,0.064714,1.660347,0.489842
...,...,...,...,...,...,...,...,...,...,...
1095,"(ItalAtlas, ItalArt)",(Florence),0.0165,0.1085,0.004,0.242424,2.234325,0.002210,1.176780,0.561706
1096,"(Florence, ItalArt)",(ItalAtlas),0.0125,0.0370,0.004,0.320000,8.648649,0.003537,1.416176,0.895570
1097,(ItalAtlas),"(Florence, ItalArt)",0.0370,0.0125,0.004,0.108108,8.648649,0.003537,1.107197,0.918354
1098,(Florence),"(ItalAtlas, ItalArt)",0.1085,0.0165,0.004,0.036866,2.234325,0.002210,1.021146,0.619672
1099,(ItalArt),"(ItalAtlas, Florence)",0.0485,0.0065,0.004,0.082474,12.688343,0.003685,1.082803,0.968142

In [22]:
asso1=association_rules(formula,metric="confidence",min_threshold=0.0)

In [23]:
asso1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(YouthBks),(ChildBks),0.2475,0.4230,0.165,0.666667,1.576044,0.060308,1.731000,0.485714
1,(ChildBks),(YouthBks),0.4230,0.2475,0.165,0.390071,1.576044,0.060308,1.233750,0.633449
2,(CookBks),(ChildBks),0.4310,0.4230,0.256,0.593968,1.404179,0.073687,1.421069,0.505870
3,(ChildBks),(CookBks),0.4230,0.4310,0.256,0.605201,1.404179,0.073687,1.441240,0.498856
4,(DoItYBks),(ChildBks),0.2820,0.4230,0.184,0.652482,1.542511,0.064714,1.660347,0.489842
...,...,...,...,...,...,...,...,...,...,...
1095,"(ItalAtlas, ItalArt)",(Florence),0.0165,0.1085,0.004,0.242424,2.234325,0.002210,1.176780,0.561706
1096,"(Florence, ItalArt)",(ItalAtlas),0.0125,0.0370,0.004,0.320000,8.648649,0.003537,1.416176,0.895570
1097,(ItalAtlas),"(Florence, ItalArt)",0.0370,0.0125,0.004,0.108108,8.648649,0.003537,1.107197,0.918354
1098,(Florence),"(ItalAtlas, ItalArt)",0.1085,0.0165,0.004,0.036866,2.234325,0.002210,1.021146,0.619672
1099,(ItalArt),"(ItalAtlas, Florence)",0.0485,0.0065,0.004,0.082474,12.688343,0.003685,1.082803,0.968142

In [24]:
asso2=association_rules(formula,metric="confidence",min_threshold=0.6)
asso2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(YouthBks),(ChildBks),0.2475,0.4230,0.1650,0.666667,1.576044,0.060308,1.731000,0.485714
1,(ChildBks),(CookBks),0.4230,0.4310,0.2560,0.605201,1.404179,0.073687,1.441240,0.498856
2,(DoItYBks),(ChildBks),0.2820,0.4230,0.1840,0.652482,1.542511,0.064714,1.660347,0.489842
3,(RefBks),(ChildBks),0.2145,0.4230,0.1515,0.706294,1.669725,0.060767,1.964548,0.510629
4,(ArtBks),(ChildBks),0.2410,0.4230,0.1625,0.674274,1.594028,0.060557,1.771427,0.490986
...,...,...,...,...,...,...,...,...,...,...
206,"(Florence, ItalArt)",(GeogBks),0.0125,0.2760,0.0090,0.720000,2.608696,0.005550,2.585714,0.624473
207,"(ItalAtlas, ItalArt)",(ItalCook),0.0165,0.1135,0.0125,0.757576,6.674676,0.010627,3.656812,0.864443
208,"(ItalAtlas, Florence)",(ItalCook),0.0065,0.1135,0.0040,0.615385,5.421891,0.003262,2.304900,0.820898
209,"(Florence, ItalArt)",(ItalCook),0.0125,0.1135,0.0095,0.760000,6.696035,0.008081,3.693750,0.861426
210,"(ItalAtlas, Florence)",(ItalArt),0.0065,0.0485,0.0040,0.615385,12.688343,0.003685,2.473900,0.927214

In [25]:
asso3=association_rules(formula,metric="confidence",min_threshold=0.7)

In [26]:
asso3

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(RefBks),(ChildBks),0.2145,0.4230,0.1515,0.706294,1.669725,0.060767,1.964548,0.510629
1,(GeogBks),(ChildBks),0.2760,0.4230,0.1950,0.706522,1.670264,0.078252,1.966074,0.554271
2,(ItalCook),(ChildBks),0.1135,0.4230,0.0850,0.748899,1.770446,0.036990,2.297877,0.490886
3,(ItalAtlas),(ChildBks),0.0370,0.4230,0.0285,0.770270,1.820970,0.012849,2.511647,0.468164
4,(ItalArt),(ChildBks),0.0485,0.4230,0.0360,0.742268,1.754771,0.015484,2.238760,0.452049
...,...,...,...,...,...,...,...,...,...,...
135,"(GeogBks, ItalArt)",(ItalCook),0.0295,0.1135,0.0240,0.813559,7.167924,0.020652,4.754864,0.886646
136,"(ItalCook, Florence)",(GeogBks),0.0175,0.2760,0.0130,0.742857,2.691511,0.008170,2.815556,0.639656
137,"(Florence, ItalArt)",(GeogBks),0.0125,0.2760,0.0090,0.720000,2.608696,0.005550,2.585714,0.624473
138,"(ItalAtlas, ItalArt)",(ItalCook),0.0165,0.1135,0.0125,0.757576,6.674676,0.010627,3.656812,0.864443
139,"(Florence, ItalArt)",(ItalCook),0.0125,0.1135,0.0095,0.760000,6.696035,0.008081,3.693750,0.861426

In [27]:
asso4=association_rules(formula,metric='confidence',min_threshold=0.9)
asso4

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(ItalCook),(CookBks),0.1135,0.4310,0.1135,1.000000,2.320186,0.064582,inf,0.641850
1,(ItalAtlas),(RefBks),0.0370,0.2145,0.0370,1.000000,4.662005,0.029063,inf,0.815680
2,(ItalArt),(ArtBks),0.0485,0.2410,0.0485,1.000000,4.149378,0.036812,inf,0.797688
3,"(ItalCook, ChildBks)",(CookBks),0.0850,0.4310,0.0850,1.000000,2.320186,0.048365,inf,0.621858
4,"(ItalAtlas, ChildBks)",(RefBks),0.0285,0.2145,0.0285,1.000000,4.662005,0.022387,inf,0.808543
5,"(ChildBks, ItalArt)",(ArtBks),0.0360,0.2410,0.0360,1.000000,4.149378,0.027324,inf,0.787344
6,"(ItalCook, YouthBks)",(CookBks),0.0590,0.4310,0.0590,1.000000,2.320186,0.033571,inf,0.604676
7,"(ItalAtlas, YouthBks)",(RefBks),0.0175,0.2145,0.0175,1.000000,4.662005,0.013746,inf,0.799491
8,"(YouthBks, ItalArt)",(ArtBks),0.0230,0.2410,0.0230,1.000000,4.149378,0.017457,inf,0.776868
9,"(DoItYBks, ItalCook)",(CookBks),0.0585,0.4310,0.0585,1.000000,2.320186,0.033287,inf,0.604355
10,"(DoItYBks, ItalArt)",(CookBks),0.0300,0.4310,0.0270,0.900000,2.088167,0.014070,5.690000,0.537228
11,"(RefBks, ItalCook)",(CookBks),0.0465,0.4310,0.0465,1.000000,2.320186,0.026458,inf,0.596749
12,"(CookBks, ItalAtlas)",(RefBks),0.0285,0.2145,0.0285,1.000000,4.662005,0.022387,inf,0.808543
13,"(ItalCook, ArtBks)",(CookBks),0.0565,0.4310,0.0565,1.000000,2.320186,0.032148,inf,0.603074
14,"(CookBks, ItalArt)",(ArtBks),0.0410,0.2410,0.0410,1.000000,4.149378,0.031119,inf,0.791449
15,"(GeogBks, ItalCook)",(CookBks),0.0640,0.4310,0.0640,1.000000,2.320186,0.036416,inf,0.607906
16,"(ItalCook, ItalAtlas)",(CookBks),0.0230,0.4310,0.0230,1.000000,2.320186,0.013087,inf,0.582395
17,"(ItalCook, ItalArt)",(CookBks),0.0375,0.4310,0.0375,1.000000,2.320186,0.021337,inf,0.591169
18,"(CookBks, ItalArt)",(ItalCook),0.0410,0.1135,0.0375,0.914634,8.058451,0.032847,10.384714,0.913354
19,"(ItalCook, Florence)",(CookBks),0.0175,0.4310,0.0175,1.000000,2.320186,0.009958,inf,0.579135
20,"(DoItYBks, ItalAtlas)",(RefBks),0.0190,0.2145,0.0190,1.000000,4.662005,0.014925,inf,0.800714
21,"(DoItYBks, ItalArt)",(ArtBks),0.0300,0.2410,0.0300,1.000000,4.149378,0.022770,inf,0.782474
22,"(ItalAtlas, ArtBks)",(RefBks),0.0180,0.2145,0.0180,1.000000,4.662005,0.014139,inf,0.799898
23,"(RefBks, ItalArt)",(ArtBks),0.0200,0.2410,0.0200,1.000000,4.149378,0.015180,inf,0.774490
24,"(GeogBks, ItalAtlas)",(RefBks),0.0205,0.2145,0.0205,1.000000,4.662005,0.016103,inf,0.801940
25,"(ItalCook, ItalAtlas)",(RefBks),0.0230,0.2145,0.0230,1.000000,4.662005,0.018066,inf,0.803992
26,"(ItalAtlas, ItalArt)",(RefBks),0.0165,0.2145,0.0165,1.000000,4.662005,0.012961,inf,0.798678
27,"(ItalAtlas, Florence)",(RefBks),0.0065,0.2145,0.0065,1.000000,4.662005,0.005106,inf,0.790639
28,"(GeogBks, ItalArt)",(ArtBks),0.0295,0.2410,0.0295,1.000000,4.149378,0.022391,inf,0.782071
29,"(ItalCook, ItalArt)",(ArtBks),0.0375,0.2410,0.0375,1.000000,4.149378,0.028463,inf,0.788571
30,"(ItalAtlas, ArtBks)",(ItalArt),0.0180,0.0485,0.0165,0.916667,18.900344,0.015627,11.418000,0.964451
31,"(ItalAtlas, ItalArt)",(ArtBks),0.0165,0.2410,0.0165,1.000000,4.149378,0.012523,inf,0.771734
32,"(Florence, ItalArt)",(ArtBks),0.0125,0.2410,0.0125,1.000000,4.149378,0.009488,inf,0.768608

In [28]:
min_length= apriori(data_p,min_support=0.0000001,use_colnames=True)
min_length

      support                                           itemsets
0      0.4230                                         (ChildBks)
1      0.2475                                         (YouthBks)
2      0.4310                                          (CookBks)
3      0.2820                                         (DoItYBks)
4      0.2145                                           (RefBks)
...       ...                                                ...
2042   0.0015  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...
2043   0.0010  (ItalCook, ItalArt, ItalAtlas, ChildBks, GeogB...
2044   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...
2045   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, GeogBk...
2046   0.0010  (ItalCook, ItalArt, CookBks, ItalAtlas, ChildB...

[2047 rows x 2 columns]

In [37]:
r=asso3[asso3.consequents==frozenset({"ArtBks"})]
r

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
10,(ItalArt),(ArtBks),0.0485,0.241,0.0485,1.000000,4.149378,0.036812,inf,0.797688
55,"(ChildBks, ItalArt)",(ArtBks),0.0360,0.241,0.0360,1.000000,4.149378,0.027324,inf,0.787344
78,"(YouthBks, ItalArt)",(ArtBks),0.0230,0.241,0.0230,1.000000,4.149378,0.017457,inf,0.776868
79,"(Florence, YouthBks)",(ArtBks),0.0255,0.241,0.0190,0.745098,3.091693,0.012855,2.977615,0.694256
98,"(CookBks, ItalArt)",(ArtBks),0.0410,0.241,0.0410,1.000000,4.149378,0.031119,inf,0.791449
114,"(DoItYBks, ItalArt)",(ArtBks),0.0300,0.241,0.0300,1.000000,4.149378,0.022770,inf,0.782474
115,"(DoItYBks, Florence)",(ArtBks),0.0315,0.241,0.0245,0.777778,3.227294,0.016908,3.415500,0.712589
118,"(RefBks, ItalArt)",(ArtBks),0.0200,0.241,0.0200,1.000000,4.149378,0.015180,inf,0.774490
125,"(GeogBks, ItalArt)",(ArtBks),0.0295,0.241,0.0295,1.000000,4.149378,0.022391,inf,0.782071
126,"(GeogBks, Florence)",(ArtBks),0.0425,0.241,0.0300,0.705882,2.928972,0.019757,2.580600,0.687815
128,"(ItalCook, ItalArt)",(ArtBks),0.0375,0.241,0.0375,1.000000,4.149378,0.028463,inf,0.788571
132,"(ItalAtlas, ItalArt)",(ArtBks),0.0165,0.241,0.0165,1.000000,4.149378,0.012523,inf,0.771734
133,"(Florence, ItalArt)",(ArtBks),0.0125,0.241,0.0125,1.000000,4.149378,0.009488,inf,0.768608